Feature/gh 155 refactoring
marartz/Gastromio pull request #204
Opened 2021-05-10 19:56 UTC by marartz

2021-05-11 22:27 UTC, ikke09 requested changes
Great Work @marartz 💪🏽🚀
Pull request is a little bit to big to cover every detail in the review. Hopefully I coverd the most crucial aspects here! I made some smaller comments. Please take a look at them 😉

2021-05-11 22:27 UTC, ikke09 commented on src/Gastromio.App/ClientApp/src/app/restaurant-admin/restaurant-admin.facade.ts
> +          console.log("restaurant: ", restaurant);
Missed debug log? 🧹

2021-05-14 09:32 UTC, marartz commented on src/Gastromio.Core/Domain/Model/Orders/OrderId.cs
> +                throw new InvalidOperationException("order id is invalid");
You are right. I changed it accordingly.

2021-05-14 09:42 UTC, marartz commented on src/Gastromio.Core/Domain/Model/Restaurants/Restaurant.cs
>              PickupInfo = pickupInfo;
I opted for a domain exception here.

2021-05-14 09:42 UTC, marartz commented on src/Gastromio.Core/Domain/Model/Restaurants/Restaurant.cs
>              ContactInfo = contactInfo;
done

2021-05-14 10:07 UTC, marartz commented on src/Gastromio.Core/Domain/Model/Users/User.cs
>              if (checkPasswordPolicy && !passwordPolicyRegex.IsMatch(password))
Done

2021-05-14 10:07 UTC, marartz commented on src/Gastromio.Core/Domain/Model/Users/User.cs
> +            var testPasswordHash = PBKDF2(password, PasswordSalt, PBKDF2_ITERATIONS, HASH_BYTES);
Ok... We'll do it in the next refactoring.

2021-05-14 10:07 UTC, marartz commented on src/Gastromio.App/ClientApp/src/app/restaurant-admin/restaurant-admin.facade.ts
> +          console.log("restaurant: ", restaurant);
Done

2021-05-14 10:08 UTC, marartz commented
@ikke09 : I'm done with your requested changes and comments. Could you review again?

2021-05-15 21:22 UTC, ikke09 approved these changes
Seems all good now! 🚀

2021-05-16 11:22 UTC, merged